### ISSUE TITLE
v2ray+ws+tls+nginx 速度问题

### ISSUE THREAD

**Issue by wilsonwu** [ToutyRater/toutyrater.github.io#10]
你好，看来你的文章资讯一个问题，之前用v2ray+kcp方式速度有6m/s，但是经常被封，所以经常要换ip和端口，还是无济于事，最后换成ws+tls+nginx伪装，刚弄好不知道会不会被封，但是速度相当慢，访问Google都要好几秒钟，请问有没有办法优化一下速度？

**Comment by ToutyRater** [comment]
请学会如果提问！
相当慢是多慢？
好几秒是多少秒？
怎么访问？
怎么配置的？
什么样的使用环境？
有没有在不同时间段测试过？
有没有做过对照实验？
