### ISSUE TITLE
网页中一处拼写错误

### ISSUE THREAD

**Issue by wfly1998** [ToutyRater/toutyrater.github.io#5]
https://github.com/ToutyRater/toutyrater.github.io/blob/c6d8b5d26cfc4d9cd4f021072b07f16454f8dd08/basic/vmess.html#L728

原文内容：
> 不过，最好还是使用 V2Ray 提供的配置检查功能（test 选项），因为可以检查 _JOSN_ 语法错误外的问题，比如说突然间手抖把 vmess 写成了 vmss，一下子就检查出来了。

JSON拼写成JOSN了。

**Comment by ToutyRater** [comment]
已修正
